# Generated by Django 5.0.7 on 2024-07-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('is_exist', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveIntegerField(blank=True, default=5, null=True)),
                ('min_basket_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, null=True)),
                ('delivery_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True)),
                ('delivery_time', models.CharField(default='30-45 dk', max_length=400)),
            ],
        ),
    ]
