# Generated by Django 5.0.6 on 2024-07-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True),
        ),
    ]
