# Generated by Django 5.0.6 on 2024-07-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_remove_restaurant_image_restaurant_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='image',
        ),
        migrations.AddField(
            model_name='offer',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
