# Generated by Django 5.0.7 on 2024-07-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_menuitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
